# 1. Le decimos a Spring Boot que cargue los secretos de este archivo oculto
spring.config.import=optional:classpath:application-secret.properties

# 2. Configuración del puerto
server.port=8080

# 3. Referencias a las variables (Spring las buscará ahora en el archivo secreto)
spring.data.mongodb.uri=${MONGO_URI}
openai.api.key=${OPENAI_API_KEY}
jwt.secret=${JWT_SECRET_KEY}